name: Build Desktop EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, desktop-port ]  # build on these branches

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle (wrapper + caching)
        uses: gradle/actions/setup-gradle@v3

      - name: Java & Gradle info
        shell: pwsh
        run: |
          java -version
          & .\gradlew.bat -v

      - name: Sanity check – list tasks
        shell: pwsh
        run: |
          & .\gradlew.bat tasks --all

      - name: Build Desktop EXE
        shell: pwsh
        run: |
          & .\gradlew.bat :desktopApp:packageExe --stacktrace --info --no-daemon

      - name: Show compose outputs
        if: always()
        shell: pwsh
        run: |
          Get-ChildItem -Recurse desktopApp\build\compose | Out-String | Write-Host

      - name: Upload EXE artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: RealmsAI-Desktop-EXE
          path: |
            desktopApp/build/compose/**/**/*.exe
            desktopApp/build/compose/**/*.exe
          if-no-files-found: warn
