name: Build Desktop EXE

on:
  workflow_dispatch:
  push:
    branches: [ desktop-port ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant wrapper permissions
        run: git update-index --chmod=+x gradlew

      - name: Build Windows EXE
        shell: bash
        run: ./gradlew :desktopApp:packageExe --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RealmsAI-Desktop-EXE
          path: desktopApp/build/compose/binaries/main/exe/**/*.exe
