name: Build Desktop EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, desktop-port ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure jpackage on PATH
        shell: pwsh
        run: |
          # put JAVA_HOME\bin on PATH so Gradle can find jpackage
          "$env:JAVA_HOME\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up Gradle (wrapper + caching)
        uses: gradle/actions/setup-gradle@v3

      - name: Java & Gradle info
        shell: pwsh
        run: |
          java -version
          where.exe java
          where.exe jpackage
          & .\gradlew.bat -v

      - name: Sanity check – list desktop tasks
        shell: pwsh
        run: |
          & .\gradlew.bat :desktopApp:tasks --all

      # Build a distributable folder/zip first (works even if jpackage misbehaves)
      - name: Build Desktop distributable
        shell: pwsh
        run: |
          & .\gradlew.bat :desktopApp:createDistributable --stacktrace --info --no-daemon

      - name: Upload distributable
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: RealmsAI-Desktop-Distributable
          path: |
            desktopApp/build/compose/**/**/distributable/**
            desktopApp/build/compose/**/distributable/**
          if-no-files-found: warn

      # Then build the .exe
      - name: Build Desktop EXE
        shell: pwsh
        run: |
          & .\gradlew.bat :desktopApp:packageExe --stacktrace --info --no-daemon

      - name: Show compose outputs
        if: always()
        shell: pwsh
        run: |
          Get-ChildItem -Recurse desktopApp\build\compose | Out-String | Write-Host

      - name: Upload EXE artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: RealmsAI-Desktop-EXE
          path: |
            desktopApp/build/compose/**/**/*.exe
            desktopApp/build/compose/**/*.exe
          if-no-files-found: warn
